//
//  LoginSceneInteractor.swift
//  SOM AI
//
//  Created by Bagas Ilham on 13/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class LoginSceneInteractor {
}

// MARK: - Extensions -

extension LoginSceneInteractor: LoginSceneInteractorInterface {
}
