//
//  LoginSceneInterfaces.swift
//  SOM AI
//
//  Created by Bagas Ilham on 13/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol LoginSceneWireframeInterface: WireframeInterface {
    func navigate(to option: LoginSceneNavigation)
}

enum LoginSceneNavigation {
    case previous
    case register
}

protocol LoginSceneViewInterface: ViewInterface {
    func animateBlurMovement()
}

protocol LoginScenePresenterInterface: PresenterInterface {
    func configure(with output: LoginScene.ViewOutput) -> LoginScene.ViewInput
    func didTapBackBarButton()
    func didTapLoginButton()
    func didTapLoginWithGoogleButton()
    func didTapRegisterButton()
}

protocol LoginSceneInteractorInterface: InteractorInterface {
}

enum LoginScene {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}
