//
//  LoginScenePresenter.swift
//  SOM AI
//
//  Created by Bagas Ilham on 13/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class LoginScenePresenter {

    // MARK: - Private properties -

    private unowned let view: LoginSceneViewInterface
    private let interactor: LoginSceneInteractorInterface
    private let wireframe: LoginSceneWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: LoginSceneViewInterface,
        interactor: LoginSceneInteractorInterface,
        wireframe: LoginSceneWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension LoginScenePresenter: LoginScenePresenterInterface {
    func configure(with output: LoginScene.ViewOutput) -> LoginScene.ViewInput {
        return LoginScene.ViewInput()
    }
    
    func didTapBackBarButton() {
        wireframe.navigate(to: .previous)
    }

    func didTapLoginButton() {
        //
        view.animateBlurMovement()
    }
    
    func didTapLoginWithGoogleButton() {
        ToastManager.shared.showErrorToast(message: "Akun tidak ditemukan. Mohon coba kembali dengan akun yang berbeda.")
    }
    
    func didTapRegisterButton() {
        wireframe.navigate(to: .register)
    }
}
