//
//  LoginSceneWireframe.swift
//  SOM AI
//
//  Created by Bagas Ilham on 13/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class LoginSceneWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = LoginSceneViewController()
        super.init(viewController: moduleViewController)

        let interactor = LoginSceneInteractor()
        let presenter = LoginScenePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LoginSceneWireframe: LoginSceneWireframeInterface {
    func navigate(to option: LoginSceneNavigation) {
        switch option {
        case .previous:
            navigationController?.popViewController(animated: true)
            
        case .register:
            guard let viewController = RegisterSceneWireframe().viewController as? RegisterSceneViewController else { return }
            viewController.delegate = self.viewController as? RegisterSceneDelegate
            
            let navigation = UINavigationController(rootViewController: viewController)
            navigation.modalPresentationStyle = .overCurrentContext
            navigation.navigationBar.isOpaque = false
            navigationController?.present(navigation, animated: false)
        }
    }
}
