//
//  RegisterScenePresenter.swift
//  SOM AI
//
//  Created by Bagas Ilham on 17/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class RegisterScenePresenter {

    // MARK: - Private properties -

    private unowned let view: RegisterSceneViewInterface
    private let interactor: RegisterSceneInteractorInterface
    private let wireframe: RegisterSceneWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: RegisterSceneViewInterface,
        interactor: RegisterSceneInteractorInterface,
        wireframe: RegisterSceneWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RegisterScenePresenter: RegisterScenePresenterInterface {
    func configure(with output: RegisterScene.ViewOutput) -> RegisterScene.ViewInput {
        return RegisterScene.ViewInput()
    }
    
    func didTapDismissButton() {
        wireframe.navigate(to: .dismiss)
    }
}
