//
//  RegisterSceneWireframe.swift
//  SOM AI
//
//  Created by Bagas Ilham on 17/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxCocoa
import RxSwift

final class RegisterSceneWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = RegisterSceneViewController()
        super.init(viewController: moduleViewController)

        let interactor = RegisterSceneInteractor()
        let presenter = RegisterScenePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension RegisterSceneWireframe: RegisterSceneWireframeInterface {
    func navigate(to option: RegisterSceneNavigation) {
        switch option {
        case .dismiss:
            viewController.dismiss(animated: false)
        }
    }
}
