//
//  RegisterSceneInteractor.swift
//  SOM AI
//
//  Created by Bagas Ilham on 17/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class RegisterSceneInteractor {
}

// MARK: - Extensions -

extension RegisterSceneInteractor: RegisterSceneInteractorInterface {
}
