//
//  RegisterSceneInterfaces.swift
//  SOM AI
//
//  Created by Bagas Ilham on 17/11/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol RegisterSceneWireframeInterface: WireframeInterface {
    func navigate(to option: RegisterSceneNavigation)
}

enum RegisterSceneNavigation {
    case dismiss
}

protocol RegisterSceneViewInterface: ViewInterface {
}

protocol RegisterScenePresenterInterface: PresenterInterface {
    func configure(with output: RegisterScene.ViewOutput) -> RegisterScene.ViewInput
    func didTapDismissButton()
}

protocol RegisterSceneInteractorInterface: InteractorInterface {
}

enum RegisterScene {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}
